### ISSUE TITLE
latencyflex2 support

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/proton-cachyos#4]
Hi,

I want to suggest the addition of latencyflex2 on proton-cachyos as optional.

First version brought very good input lag reduction on mouse control resulting in better accuracy after adding it here.

Much more noticeable compared to activating reflex on windows.

https://github.com/ishitatsuyuki/latencyflex2

I suppose the second version makes more sense, as to have packages updated yet with latencyflex2. https://github.com/Zeioth/latencyflex2-installer/blob/main/install.sh#L21

And since you need the dll per game, leave it together with instructions, to be copied when needed https://lfx2.ishitatsuy.uk/shim/installing.html#installing-the-core-module

**Comment by ptr1337** [comment]
LF2 is not even yet fully released, therefore it shouldnt be implemented,

**Comment by dougg0k** [comment]
Maybe have an additional `proton-cachyos-lfx2` version?

**Comment by ptr1337** [comment]
lfx2 is not ready yet, therefore it will not be added.
