### ISSUE TITLE
wine: could not load ntdll.so

### ISSUE THREAD

**Issue by kirisaki-vk** [CachyOS/proton-cachyos#5]
I've tried running some of my games with proton-cachyos but all of them gives me this kind of error

## Informations
- OS : CachyOS
- Kernel: `6.12.3-1-cachyos`
- proton-cachyos version: `1:9.0.20241206-1`

## Logs

```
Proton: /.../Games/ZenlessZoneZero Game/ZenlessZoneZero.exe
Proton: Executable a unix path, launching with /unix option.
wine: could not load ntdll.so: /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib//wine/ntdll.so: cannot open shared object file: No such file or directory
Command exited with status: 1
```

Full logs can be seen [here](https://gist.github.com/kirisaki-vk/4ef9c230495f73af4725c83f2294a73a)

**Comment by loathingKernel** [comment]
Invalid configuration, follow the guide in the CachyOS wiki. In this case, you need to set `UMU_NO_RUNTIME=1`
